"""empty message

Revision ID: 69e30549a017
Revises: 4448a2d8e542
Create Date: 2024-02-28 02:51:41.085155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e30549a017'
down_revision = '4448a2d8e542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
